name: Update GitHub Stars

on:
  # 每天自动运行
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点运行
  
  # 手动触发
  workflow_dispatch:
  
  # 当有新的star操作时触发
  watch:
    types: [started]

jobs:
  update-stars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Run stars update script
        run: python update_stars.py
        env:
          GITHUB_USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GITHUB_REPO: ${{ github.event.repository.name }}
